name: presensi
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  barcode_scan2: ^4.2.0
  calendar_timeline: ^1.1.2
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.1
  http: ^1.2.1
  image_picker: ^1.1.0
  intl: ^0.17.0
  path: ^1.8.3
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.6
  

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter  

flutter:  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/nav/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
